[project]
name = "svo2gradslam"
version = "0.1"

[build-backend]
requires = ["setuptools"]
build-backed = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
include-package-data = true